// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type SubsystemProfile struct {
	Name        string
	ProfileID   string
	ProfileUuid string
	RawProfile  []byte
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
