// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
	"strings"
)

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM subsystem_profiles WHERE name = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, name)
	return err
}

const getAllProfileInfos = `-- name: GetAllProfileInfos :many
SELECT
  name,
  profile_id,
  profile_uuid
FROM
  subsystem_profiles
`

type GetAllProfileInfosRow struct {
	Name        string
	ProfileID   string
	ProfileUuid string
}

func (q *Queries) GetAllProfileInfos(ctx context.Context) ([]GetAllProfileInfosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProfileInfos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProfileInfosRow
	for rows.Next() {
		var i GetAllProfileInfosRow
		if err := rows.Scan(&i.Name, &i.ProfileID, &i.ProfileUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileInfos = `-- name: GetProfileInfos :many
SELECT
  name,
  profile_id,
  profile_uuid
FROM
  subsystem_profiles
WHERE
  name IN (/*SLICE:names*/?)
`

type GetProfileInfosRow struct {
	Name        string
	ProfileID   string
	ProfileUuid string
}

func (q *Queries) GetProfileInfos(ctx context.Context, names []string) ([]GetProfileInfosRow, error) {
	query := getProfileInfos
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfileInfosRow
	for rows.Next() {
		var i GetProfileInfosRow
		if err := rows.Scan(&i.Name, &i.ProfileID, &i.ProfileUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawProfiles = `-- name: GetRawProfiles :many
SELECT
  name,
  raw_profile
FROM
  subsystem_profiles
WHERE
  name IN (/*SLICE:names*/?)
`

type GetRawProfilesRow struct {
	Name       string
	RawProfile []byte
}

func (q *Queries) GetRawProfiles(ctx context.Context, names []string) ([]GetRawProfilesRow, error) {
	query := getRawProfiles
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRawProfilesRow
	for rows.Next() {
		var i GetRawProfilesRow
		if err := rows.Scan(&i.Name, &i.RawProfile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
