FROM --platform=$BUILDPLATFORM golang:1.21 AS builder

WORKDIR /go/app

COPY . .

ARG TARGETOS TARGETARCH

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 make nanocmd-$TARGETOS-$TARGETARCH

FROM gcr.io/distroless/static

ARG TARGETOS TARGETARCH

COPY --from=builder /go/app/nanocmd-$TARGETOS-$TARGETARCH /app/nanocmd

EXPOSE 9003

VOLUME ["/app/db"]

WORKDIR /app

ENTRYPOINT ["/app/nanocmd"]
