// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const clearWorkflowStatus = `-- name: ClearWorkflowStatus :exec
DELETE FROM
  wf_status
WHERE
  enrollment_id = ?
`

func (q *Queries) ClearWorkflowStatus(ctx context.Context, enrollmentID string) error {
	_, err := q.db.ExecContext(ctx, clearWorkflowStatus, enrollmentID)
	return err
}

const createIDCommand = `-- name: CreateIDCommand :exec
INSERT INTO id_commands
  (enrollment_id, command_uuid, step_id, request_type, last_push)
VALUES
  (?, ?, ?, ?, ?)
`

type CreateIDCommandParams struct {
	EnrollmentID string
	CommandUuid  string
	StepID       int64
	RequestType  string
	LastPush     sql.NullTime
}

// The only INSERT INTO id_commands. StoreStep always creates the steps row
// first, so an existing step can never gain a reference -- which is what lets
// SelectUnreferencedStepIDs run without a lock. Do not add a path that points
// new id_commands at an existing step.
func (q *Queries) CreateIDCommand(ctx context.Context, arg CreateIDCommandParams) error {
	_, err := q.db.ExecContext(ctx, createIDCommand,
		arg.EnrollmentID,
		arg.CommandUuid,
		arg.StepID,
		arg.RequestType,
		arg.LastPush,
	)
	return err
}

const createStep = `-- name: CreateStep :execlastid
INSERT INTO steps
  (workflow_name, instance_id, step_name, context, not_until, timeout)
VALUES
  (?, ?, ?, ?, ?, ?)
`

type CreateStepParams struct {
	WorkflowName string
	InstanceID   string
	StepName     sql.NullString
	Context      []byte
	NotUntil     sql.NullTime
	Timeout      sql.NullTime
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStep,
		arg.WorkflowName,
		arg.InstanceID,
		arg.StepName,
		arg.Context,
		arg.NotUntil,
		arg.Timeout,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createStepCommand = `-- name: CreateStepCommand :exec
INSERT INTO step_commands
  (step_id, command_uuid, request_type, command)
VALUES
  (?, ?, ?, ?)
`

type CreateStepCommandParams struct {
	StepID      int64
	CommandUuid string
	RequestType string
	Command     []byte
}

func (q *Queries) CreateStepCommand(ctx context.Context, arg CreateStepCommandParams) error {
	_, err := q.db.ExecContext(ctx, createStepCommand,
		arg.StepID,
		arg.CommandUuid,
		arg.RequestType,
		arg.Command,
	)
	return err
}

const deleteIDCommands = `-- name: DeleteIDCommands :exec
DELETE FROM
  id_commands
WHERE
  enrollment_id = ?
`

func (q *Queries) DeleteIDCommands(ctx context.Context, enrollmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteIDCommands, enrollmentID)
	return err
}

const deleteIDCommandsByWorkflowName = `-- name: DeleteIDCommandsByWorkflowName :exec
DELETE FROM
  id_commands
WHERE
  enrollment_id = ? AND
  step_id IN (
    SELECT
      id
    FROM
      steps
    WHERE
      workflow_name = ?
  )
`

type DeleteIDCommandsByWorkflowNameParams struct {
	EnrollmentID string
	WorkflowName string
}

// Scoped by workflow name rather than by a list of step IDs, so the statement
// is a fixed size: an enrollment's step IDs are unbounded, and 65535
// placeholders is a hard limit.
//
// MySQL 8 semi-joins this. For an enrollment holding few rows it drives from
// id_commands and does one primary key lookup per row; for one holding very
// many it flips to scanning the workflow_name index instead. Measured against
// 100k steps sharing a name: 0.04ms for a 5-row enrollment, 337ms for a
// 50,000-row one.
func (q *Queries) DeleteIDCommandsByWorkflowName(ctx context.Context, arg DeleteIDCommandsByWorkflowNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteIDCommandsByWorkflowName, arg.EnrollmentID, arg.WorkflowName)
	return err
}

const deleteStepCommandsByStepIDs = `-- name: DeleteStepCommandsByStepIDs :exec
DELETE FROM
  step_commands
WHERE
  step_id IN (/*SLICE:step_ids*/?)
`

func (q *Queries) DeleteStepCommandsByStepIDs(ctx context.Context, stepIds []int64) error {
	query := deleteStepCommandsByStepIDs
	var queryParams []interface{}
	if len(stepIds) > 0 {
		for _, v := range stepIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:step_ids*/?", strings.Repeat(",?", len(stepIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:step_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteStepsByStepIDs = `-- name: DeleteStepsByStepIDs :exec
DELETE FROM
  steps
WHERE
  id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteStepsByStepIDs(ctx context.Context, ids []int64) error {
	query := deleteStepsByStepIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getIDCommandsByStepIDAndLock = `-- name: GetIDCommandsByStepIDAndLock :many
SELECT
  command_uuid,
  request_type,
  result,
  completed
FROM
  id_commands
WHERE
  enrollment_id = ? AND
  step_id = ?
FOR UPDATE
`

type GetIDCommandsByStepIDAndLockParams struct {
	EnrollmentID string
	StepID       int64
}

type GetIDCommandsByStepIDAndLockRow struct {
	CommandUuid string
	RequestType string
	Result      []byte
	Completed   bool
}

// Reads and locks this enrollment's rows for the step, and only those. Step
// completion is decided from this result, so it has to lock: the worker's
// timeout sweep deletes these same rows on a timer, serialized with nothing
// (see RetrieveTimedOutSteps). No other enrollment owns them, so nothing
// else ever waits here.
//
// Do not add joins. "step_id = ?" already says what a steps join would, and a
// steps join under FOR UPDATE locks the one row the whole fan-out shares.
func (q *Queries) GetIDCommandsByStepIDAndLock(ctx context.Context, arg GetIDCommandsByStepIDAndLockParams) ([]GetIDCommandsByStepIDAndLockRow, error) {
	rows, err := q.db.QueryContext(ctx, getIDCommandsByStepIDAndLock, arg.EnrollmentID, arg.StepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIDCommandsByStepIDAndLockRow
	for rows.Next() {
		var i GetIDCommandsByStepIDAndLockRow
		if err := rows.Scan(
			&i.CommandUuid,
			&i.RequestType,
			&i.Result,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutstandingIDs = `-- name: GetOutstandingIDs :many
SELECT DISTINCT
  c.enrollment_id
FROM
  id_commands c
  JOIN steps s
    ON s.id = c.step_id
WHERE
  c.enrollment_id IN (/*SLICE:ids*/?) AND
  c.completed = 0 AND
  s.workflow_name = ?
`

type GetOutstandingIDsParams struct {
	Ids          []string
	WorkflowName string
}

func (q *Queries) GetOutstandingIDs(ctx context.Context, arg GetOutstandingIDsParams) ([]string, error) {
	query := getOutstandingIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.WorkflowName)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var enrollment_id string
		if err := rows.Scan(&enrollment_id); err != nil {
			return nil, err
		}
		items = append(items, enrollment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestType = `-- name: GetRequestType :one
SELECT
  request_type
FROM
  id_commands
WHERE
  enrollment_id = ? AND
  command_uuid = ?
`

type GetRequestTypeParams struct {
	EnrollmentID string
	CommandUuid  string
}

func (q *Queries) GetRequestType(ctx context.Context, arg GetRequestTypeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRequestType, arg.EnrollmentID, arg.CommandUuid)
	var request_type string
	err := row.Scan(&request_type)
	return request_type, err
}

const getStepByID = `-- name: GetStepByID :one
SELECT
  workflow_name,
  instance_id,
  step_name,
  context
FROM
  steps
WHERE
  id = ?
`

type GetStepByIDRow struct {
	WorkflowName string
	InstanceID   string
	StepName     sql.NullString
	Context      []byte
}

func (q *Queries) GetStepByID(ctx context.Context, id int64) (GetStepByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStepByID, id)
	var i GetStepByIDRow
	err := row.Scan(
		&i.WorkflowName,
		&i.InstanceID,
		&i.StepName,
		&i.Context,
	)
	return i, err
}

const getStepIDByCommandUUID = `-- name: GetStepIDByCommandUUID :one
SELECT
  step_id
FROM
  id_commands
WHERE
  enrollment_id = ? AND
  command_uuid = ?
`

type GetStepIDByCommandUUIDParams struct {
	EnrollmentID string
	CommandUuid  string
}

func (q *Queries) GetStepIDByCommandUUID(ctx context.Context, arg GetStepIDByCommandUUIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStepIDByCommandUUID, arg.EnrollmentID, arg.CommandUuid)
	var step_id int64
	err := row.Scan(&step_id)
	return step_id, err
}

const getStepIDsByEnrollmentID = `-- name: GetStepIDsByEnrollmentID :many
SELECT DISTINCT
  step_id
FROM
  id_commands
WHERE
  enrollment_id = ?
`

func (q *Queries) GetStepIDsByEnrollmentID(ctx context.Context, enrollmentID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getStepIDsByEnrollmentID, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var step_id int64
		if err := rows.Scan(&step_id); err != nil {
			return nil, err
		}
		items = append(items, step_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepIDsByEnrollmentIDAndWorkflowName = `-- name: GetStepIDsByEnrollmentIDAndWorkflowName :many
SELECT DISTINCT
  c.step_id
FROM
  id_commands c
  INNER JOIN steps s
    ON c.step_id = s.id
WHERE
  c.enrollment_id = ? AND
  s.workflow_name = ?
`

type GetStepIDsByEnrollmentIDAndWorkflowNameParams struct {
	EnrollmentID string
	WorkflowName string
}

func (q *Queries) GetStepIDsByEnrollmentIDAndWorkflowName(ctx context.Context, arg GetStepIDsByEnrollmentIDAndWorkflowNameParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getStepIDsByEnrollmentIDAndWorkflowName, arg.EnrollmentID, arg.WorkflowName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var step_id int64
		if err := rows.Scan(&step_id); err != nil {
			return nil, err
		}
		items = append(items, step_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowLastStarted = `-- name: GetWorkflowLastStarted :one
SELECT
  last_created_unix
FROM
  wf_status
WHERE
  enrollment_id = ? AND
  workflow_name = ?
`

type GetWorkflowLastStartedParams struct {
	EnrollmentID string
	WorkflowName string
}

func (q *Queries) GetWorkflowLastStarted(ctx context.Context, arg GetWorkflowLastStartedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowLastStarted, arg.EnrollmentID, arg.WorkflowName)
	var last_created_unix int64
	err := row.Scan(&last_created_unix)
	return last_created_unix, err
}

const removeIDCommandsByStepID = `-- name: RemoveIDCommandsByStepID :exec
DELETE FROM
  id_commands
WHERE
  enrollment_id = ? AND
  step_id = ?
`

type RemoveIDCommandsByStepIDParams struct {
	EnrollmentID string
	StepID       int64
}

func (q *Queries) RemoveIDCommandsByStepID(ctx context.Context, arg RemoveIDCommandsByStepIDParams) error {
	_, err := q.db.ExecContext(ctx, removeIDCommandsByStepID, arg.EnrollmentID, arg.StepID)
	return err
}

const selectStepIDsForDelete = `-- name: SelectStepIDsForDelete :many
SELECT
  id
FROM
  steps
WHERE
  id IN (/*SLICE:ids*/?)
ORDER BY
  id
FOR UPDATE SKIP LOCKED
`

// Claims steps for collection. Rows another collector already holds are not
// returned, so nobody ever waits here: whoever arrives first collects, the
// rest move on and leave the step to them.
func (q *Queries) SelectStepIDsForDelete(ctx context.Context, ids []int64) ([]int64, error) {
	query := selectStepIDsForDelete
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUnreferencedStepIDs = `-- name: SelectUnreferencedStepIDs :many
SELECT
  s.id
FROM
  steps s
WHERE
  s.id IN (/*SLICE:ids*/?) AND
  NOT EXISTS (
    SELECT
      1
    FROM
      id_commands c
    WHERE
      c.step_id = s.id
  )
`

// Reports which of ids nothing refers to any more. Needs no lock, because
// "unreferenced" is a terminal state: see CreateIDCommand.
//
// Must run outside a transaction, after the caller's own deletes have
// committed. Under REPEATABLE READ a caller asking this mid-transaction is
// served from its own snapshot, so its peers' committed deletes are invisible
// to it and every one of them concludes the step is still in use.
func (q *Queries) SelectUnreferencedStepIDs(ctx context.Context, ids []int64) ([]int64, error) {
	query := selectUnreferencedStepIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIDCommand = `-- name: UpdateIDCommand :exec
UPDATE
  id_commands
SET
  completed = ?,
  result = ?
WHERE
  enrollment_id = ? AND
  command_uuid = ?
LIMIT 1
`

type UpdateIDCommandParams struct {
	Completed    bool
	Result       []byte
	EnrollmentID string
	CommandUuid  string
}

func (q *Queries) UpdateIDCommand(ctx context.Context, arg UpdateIDCommandParams) error {
	_, err := q.db.ExecContext(ctx, updateIDCommand,
		arg.Completed,
		arg.Result,
		arg.EnrollmentID,
		arg.CommandUuid,
	)
	return err
}

const updateIDCommandTimestamp = `-- name: UpdateIDCommandTimestamp :exec
UPDATE
  id_commands
SET
  updated_at = CURRENT_TIMESTAMP
WHERE
  enrollment_id = ? AND
  command_uuid = ?
LIMIT 1
`

type UpdateIDCommandTimestampParams struct {
	EnrollmentID string
	CommandUuid  string
}

func (q *Queries) UpdateIDCommandTimestamp(ctx context.Context, arg UpdateIDCommandTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateIDCommandTimestamp, arg.EnrollmentID, arg.CommandUuid)
	return err
}
